### ISSUE TITLE
Compitable with openssl 1.1

### ISSUE THREAD

**Issue by retX0** [rnapier/RNCryptor-C#4]
Cannot compile with opesnssl v1.1.1d, It seem like api changed with the latest openssl.
I just got  error ` variable has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        hmac_ctx;` when I use 1.1.1 to complie this library.

**Comment by muquit** [comment]
Please try v1.06.
Thanks.

**Comment by retX0** [comment]
It's works for me, thanks.
